rename_columns = {
        "Employee Id":"Employee ID",
        "CCP Name":"CCP Name",
        "Team Leader":"Team Leader",
        "Manager":"Manager",
        "Tenure":"Tenure",
        "FIG":"FIG",
        "Site":"Site",
        "Interaction ID":"Interaction ID",
        "Call Date":"Call Date",
        "CHT (sec/s)":"CHT (sec/s)",
        "Card Type":"Card Type",
        "Caller Type":"Caller Type",
        "Call Reason":"Call Reason",
        "Monitoring Date":"Monitoring Date",
        "Monitored By":"Monitored By",
        "Warm Welcome-Opportunities":"Warm Welcome-Opportunities",
        "Human Connection (Listen)-Opportunities":"Human Connection (Listen)-Opportunities",
        "Acknowledge Emotion (Acknowledge)-Opportunities":"Acknowledge Emotion (Acknowledge)-Opportunities",
        "Take Ownership-Opportunities":"Take Ownership-Opportunities",
        "Discover Solutions (Explore)-Opportunities":"Discover Solutions (Explore)-Opportunities",
        "Recognize and Promote Relationship-Opportunities":"Recognize and Promote Relationship-Opportunities",
        "Share a Relevant Offer or Message (Recommend)-Opportunities":"Share a Relevant Offer or Message (Recommend)-Opportunities",
        "Emphasize Resolution/Recap Actions-Opportunities":"Emphasize Resolution/Recap Actions-Opportunities",
        "Show Appreciation-Opportunities":"Show Appreciation-Opportunities",
        "OPEN WITH CONNECTION-Comment/s":"OPEN WITH CONNECTION-Comment/s",
        "COMMIT TO SOLVE-Comment/s":"COMMIT TO SOLVE-Comment/s",
        "DEEPEN RELATIONSHIP-Comment/s":"DEEPEN RELATIONSHIP-Comment/s",
        "CLOSE WITH CONFIDENCE-Comment/s":"CLOSE WITH CONFIDENCE-Comment/s",
        "VG Error Category":"VG Error Category",
        "HOC":"HOC",
        "Hotline":"Hotline",
        "PP Errors":"PP Errors",
        "COMPLIANCE OBSERVATIONS":"COMPLIANCE OBSERVATIONS",
        "Listen":"Listen",
        "Acknowledge":"Acknowledge",
        "Explore":"Explore",
        "Recommend":"Recommend",
        "Offer Type/Status":"Offer Type/Status",
        "RTF":"RTF",
        "RCR":"RCR",
        "Call Handling Time":"Call Handling Time",
        "Complaints":"Complaints",
        "Extended Product":"Extended Product",
        "OPEN - Call Segment In Seconds":"OPEN - Call Segment In Seconds",
        "SOLVE - Call Segment In Seconds":"SOLVE - Call Segment In Seconds",
        "DEEPEN RELATIONSHIP - Call Segment In Seconds":"DEEPEN RELATIONSHIP - Call Segment In Seconds",
        "CLOSE WITH CONFIDENCE - Call Segment In Seconds":"CLOSE WITH CONFIDENCE - Call Segment In Seconds",
        "Total Time of Call - Call Segment In Seconds":"Total Time of Call - Call Segment In Seconds",
        "Waste (Actual CHT - Total Time Spent)":"Waste (Actual CHT - Total Time Spent)",
        "Driver 1":"Driver 1",
        "Driver 2":"Driver 2",
        "Driver 3":"Driver 3",
        "Driver 4":"Driver 4",
        "Feedback Is Accepted":"Feedback   Is Accepted",
        "Feedback Date":"Feedback Date",
        "Feedback With CCP Acknowledgement_Do I understand Reason for Non-Promotor rating?":"Feedback With CCP Acknowledgement_Do I understand Reason for Non-Promotor rating?",
        "Feedback With CCP Acknowledgement_Can I do better Next Time?":"Feedback With CCP Acknowledgement_Can I do better Next Time?",
        "Feedback With CCP Acknowledgement_Sharing my Commitment.":"Feedback With CCP Acknowledgement_Sharing my Commitment.",
        "Feedback with TL_Acknowledgement":"Feedback with TL_Acknowledgement",
        "Feedback With TL Acknowledgement_Do I understand Reason for Non-Promotor rating?":"Feedback With TL Acknowledgement_Do I understand Reason for Non-Promotor rating?",
        "Feedback With TL Acknowledgement_Can I do better Next Time?":"Feedback With TL Acknowledgement_Can I do better Next Time?",
        "Feedback With TL Acknowledgement_Sharing my Commitment.":"Feedback With TL Acknowledgement_Sharing my Commitment.",
        "Spoken Words Q1":"Spoken Words - Q1",
        "Spoken Words Q2":"Spoken Words - Q2",
        "Spoken Words Q3":"Spoken Words - Q3",
        "Spoken Words Q4":"Spoken Words - Q4",
        "Spoken Words - Total":"Spoken Words - Total",
        "Pitch and Tone Q1":"Pitch and Tone - Q1",
        "Pitch and Tone Q2":"Pitch and Tone - Q2",
        "Pitch and Tone Q3":"Pitch and Tone - Q3",
        "Pitch and Tone Q4":"Pitch and Tone - Q4",
        "Pitch and Tone - Total":"Pitch and Tone - Total",
        " Cross-Talk Q1":"Cross-Talk - Q1",
        " Cross-Talk Q2":"Cross-Talk - Q2",
        " Cross-Talk Q3":"Cross-Talk - Q3",
        " Cross-Talk Q4":"Cross-Talk - Q4",
        "Cross-Talk - Total":"Cross-Talk - Total",
        "Emotion Detection Q1":"Emotion Detection - Q1",
        "Emotion Detection Q2":"Emotion Detection - Q2",
        "Emotion Detection Q3":"Emotion Detection - Q3",
        "Emotion Detection Q4":"Emotion Detection - Q4",
        "Emotion Detection - Total":"Emotion Detection - Total",
        "Silence and Hold Time Q1":"Silence and Hold Time - Q1",
        "Silence and Hold Time Q2":"Silence and Hold Time - Q2",
        "Silence and Hold Time Q3":"Silence and Hold Time - Q3",
        "Silence and Hold Time Q4":"Silence and Hold Time - Q4",
        "Silence and Hold Time - Total":"Silence and Hold Time - Total",
        "Resolution of the Call Q1":"Resolution of the Call - Q1",
        "Resolution of the Call Q2":"Resolution of the Call - Q2",
        "Resolution of the Call Q3":"Resolution of the Call - Q3",
        "Resolution of the Call Q4":"Resolution of the Call - Q4",
        "rctotal":"Resolution of Call Total",
        "Monitered Employee Id":"Monitered Employee Id",
        "Sales Practice Review ":"Sales Practice Review",
        " Business Integrity ":"Business Integrity",
        "Misconduct Behavior":"Misconduct Behavior",
        "Severity Level":"Severity Level"
    }

segment_to_drop_columns = [
    "Warm Welcome-Opportunities",
    "Human Connection (Listen)-Opportunities",
    "Acknowledge Emotion (Acknowledge)-Opportunities",
    "Take Ownership-Opportunities",
    "Discover Solutions (Explore)-Opportunities",
    "Recognize and Promote Relationship-Opportunities",
    "Share a Relevant Offer or Message (Recommend)-Opportunities",
    "Emphasize Resolution/Recap Actions-Opportunities",
    "Show Appreciation-Opportunities",
    "OPEN WITH CONNECTION-Comment/s",
    "COMMIT TO SOLVE-Comment/s",
    "DEEPEN RELATIONSHIP-Comment/s",
    "CLOSE WITH CONFIDENCE-Comment/s",
    "VG Error Category",
    "HOC",
    "Hotline",
    "PP Errors",
    "COMPLIANCE OBSERVATIONS",
    "Listen",
    "Acknowledge",
    "Explore",
    "Recommend",
    "Offer Type/Status",
    "RTF",
    "RCR",
    "Call Handling Time",
    "Complaints",
    "Extended Product",
    "Total Time of Call - Call Segment In Seconds",
    "Waste (Actual CHT - Total Time Spent)",
    "Driver 1",
    "Driver 2",
    "Driver 3",
    "Driver 4",
    "Feedback is Accepted",
    "Feedback Date",
    "Feedback With CCP Acknowledgement_Do I understand Reason for Non-Promotor rating?",
    "Feedback With CCP Acknowledgement_Can I do better Next Time?",
    "Feedback With CCP Acknowledgement_Sharing my Commitment.",
    "Feedback with TL_Acknowledgement",
    "Feedback With TL Acknowledgement_Do I understand Reason for Non-Promotor rating?",
    "Feedback With TL Acknowledgement_Can I do better Next Time?",
    "Feedback With TL Acknowledgement_Sharing my Commitment.",
    "Spoken Words - OPEN",
    "Spoken Words - SOLVE",
    "Spoken Words - DEEPEN RELATIONSHIP",
    "Spoken Words - CLOSE WITH CONFIDENCE",
    "Spoken Words - Total",
    "Pitch and Tone - OPEN",
    "Pitch and Tone - SOLVE",
    "Pitch and Tone - DEEPEN RELATIONSHIP",
    "Pitch and Tone - CLOSE WITH CONFIDENCE",
    "Pitch and Tone - Total",
    "Cross-Talk - OPEN",
    "Cross-Talk - SOLVE",
    "Cross-Talk - DEEPEN RELATIONSHIP",
    "Cross-Talk - CLOSE WITH CONFIDENCE",
    "Cross-Talk - Total",
    "Emotion Detection - OPEN",
    "Emotion Detection - SOLVE",
    "Emotion Detection - DEEPEN RELATIONSHIP",
    "Emotion Detection - CLOSE WITH CONFIDENCE",
    "Emotion Detection - Total",
    "Silence and Hold Time - OPEN",
    "Silence and Hold Time - SOLVE",
    "Silence and Hold Time - DEEPEN RELATIONSHIP",
    "Silence and Hold Time - CLOSE WITH CONFIDENCE",
    "Silence and Hold Time - Total",
    "Resolution of the Call - OPEN",
    "Resolution of the Call - SOLVE",
    "Resolution of the Call - DEEPEN RELATIONSHIP",
    "Resolution of the Call - CLOSE WITH CONFIDENCE",
    "Resolution of Call Total",
    "Monitered Employee Id",
    "TL=Monitored By",
    "Spoken Words - Q1",
    "Spoken Words - Q2",
    "Spoken Words - Q3",
    "Spoken Words - Q4",
    "Pitch and Tone - Q1",
    "Pitch and Tone - Q2",
    "Pitch and Tone - Q3",
    "Pitch and Tone - Q4",
    "Cross-Talk - Q1",
    "Cross-Talk - Q2",
    "Cross-Talk - Q3",
    "Cross-Talk - Q4",
    "Emotion Detection - Q1",
    "Emotion Detection - Q2",
    "Emotion Detection - Q3",
    "Emotion Detection - Q4",
    "Silence and Hold Time - Q1",
    "Silence and Hold Time - Q2",
    "Silence and Hold Time - Q3",
    "Silence and Hold Time - Q4",
    "Resolution of the Call - Q1",
    "Resolution of the Call - Q2",
    "Resolution of the Call - Q3",
    "Resolution of the Call - Q4",
    "Spoken Words - Total - AVERAGE",
    "Pitch and Tone - Total - AVERAGE",
    "Cross-Talk - Total - AVERAGE",
    "Emotion Detection - Total - AVERAGE",
    "Silence and Hold Time - Total - AVERAGE",
    "Resolution of the Call - Total - AVERAGE",
    "OPEN - AVERAGE",
    "SOLVE - AVERAGE",
    "DEEPEN RELATIONSHIP - AVERAGE",
    "CLOSE WITH CONFIDENCE - AVERAGE",
    "VIBES", "Warm Welcome",
    "Human Connection (Listen)",
    "Acknowledge Emotion (Acknowledge)",
    "Take Ownership",
    "Discover Solutions (Explore)",
    "Recognize and Promote Relationship",
    "Share a Relevant Offer or Message (Recommend)",
    "Emphasize Resolution/Recap Actions",
    "Show Appreciation",
    "Q1",
    "Q2",
    "Q3",
    "Q4",
    "VIBES Target",
    "HOC - Met",
    "VG Error - Met",
    "Hotline - Met",
    "PP Error - Met",
    "Error - Met",
    "Listen - Met", 
    "Acknowledge - Met",
    "Explore - Met",
    "Recommend - Met",
    "VG LAER - Met",
    "RTF - Met",
    "CFR - Met",
    "CHT - Met",
    "Complaints - Met",
    "Sales Practice Review",
    "Business Integrity",
    "Misconduct Behavior",
    "Severity Level",
    "FIG",
    "Call Date",
    "CCP_1",
    "TL",
    "Caller Type",
    'Acknowledge',
    "Explore CVP and Identify Clues",
    "Listen and Discover",
    "Connect a Relevant Offer",
    "Transition with a Relevant Statement",
    "Communicate Features of the Offer",
    "Personalize Value and Benefit",
    "Process the Offer Compliantly",
    "Offer Status",
    "Offer Type"
]

behavior_to_drop_columns = [
    'Call Date',
    "Warm Welcome-Opportunities",
    "Human Connection (Listen)-Opportunities",
    "Acknowledge Emotion (Acknowledge)-Opportunities",
    "Take Ownership-Opportunities",
    "Discover Solutions (Explore)-Opportunities",
    "Recognize and Promote Relationship-Opportunities",
    "Share a Relevant Offer or Message (Recommend)-Opportunities",
    "Emphasize Resolution/Recap Actions-Opportunities",
    "Show Appreciation-Opportunities",
    "OPEN WITH CONNECTION-Comment/s",
    "COMMIT TO SOLVE-Comment/s",
    "DEEPEN RELATIONSHIP-Comment/s",
    "CLOSE WITH CONFIDENCE-Comment/s",
    "VG Error Category",
    "HOC",
    "Hotline",
    "PP Errors",
    "COMPLIANCE OBSERVATIONS",
    "Listen",
    "Explore",
    "Recommend",
    "Offer Type/Status",
    "RTF",
    "RCR",
    "Call Handling Time",
    "Complaints",
    "Extended Product",
    "Total Time of Call - Call Segment In Seconds",
    "Waste (Actual CHT - Total Time Spent)",
    "Driver 1",
    "Driver 2",
    "Driver 3",
    "Driver 4",
    "Feedback is Accepted",
    "Feedback Date",
    "Feedback With CCP Acknowledgement_Do I understand Reason for Non-Promotor rating?",
    "Feedback With CCP Acknowledgement_Can I do better Next Time?",
    "Feedback With CCP Acknowledgement_Sharing my Commitment.",
    "Feedback with TL_Acknowledgement",
    "Feedback With TL Acknowledgement_Do I understand Reason for Non-Promotor rating?",
    "Feedback With TL Acknowledgement_Can I do better Next Time?",
    "Feedback With TL Acknowledgement_Sharing my Commitment.",
    "Spoken Words - OPEN",
    "Spoken Words - SOLVE",
    "Spoken Words - DEEPEN RELATIONSHIP",
    "Spoken Words - CLOSE WITH CONFIDENCE",
    "Spoken Words - Total",
    "Pitch and Tone - OPEN",
    "Pitch and Tone - SOLVE",
    "Pitch and Tone - DEEPEN RELATIONSHIP",
    "Pitch and Tone - CLOSE WITH CONFIDENCE",
    "Pitch and Tone - Total",
    "Cross-Talk - OPEN",
    "Cross-Talk - SOLVE",
    "Cross-Talk - DEEPEN RELATIONSHIP",
    "Cross-Talk - CLOSE WITH CONFIDENCE",
    "Cross-Talk - Total",
    "Emotion Detection - OPEN",
    "Emotion Detection - SOLVE",
    "Emotion Detection - DEEPEN RELATIONSHIP",
    "Emotion Detection - CLOSE WITH CONFIDENCE",
    "Emotion Detection - Total",
    "Silence and Hold Time - OPEN",
    "Silence and Hold Time - SOLVE",
    "Silence and Hold Time - DEEPEN RELATIONSHIP",
    "Silence and Hold Time - CLOSE WITH CONFIDENCE",
    "Silence and Hold Time - Total",
    "Resolution of the Call - OPEN",
    "Resolution of the Call - SOLVE",
    "Resolution of the Call - DEEPEN RELATIONSHIP",
    "Resolution of the Call - CLOSE WITH CONFIDENCE",
    "Resolution of Call Total",
    "Spoken Words - Q1",
    "Spoken Words - Q2",
    "Spoken Words - Q3",
    "Spoken Words - Q4",
    "Pitch and Tone - Q1",
    "Pitch and Tone - Q2",
    "Pitch and Tone - Q3",
    "Pitch and Tone - Q4",
    "Cross-Talk - Q1",
    "Cross-Talk - Q2",
    "Cross-Talk - Q3",
    "Cross-Talk - Q4",
    "Emotion Detection - Q1",
    "Emotion Detection - Q2",
    "Emotion Detection - Q3",
    "Emotion Detection - Q4",
    "Silence and Hold Time - Q1",
    "Silence and Hold Time - Q2",
    "Silence and Hold Time - Q3",
    "Silence and Hold Time - Q4",
    "Resolution of the Call - Q1",
    "Resolution of the Call - Q2",
    "Resolution of the Call - Q3",
    "Resolution of the Call - Q4",
    "Spoken Words - Total - AVERAGE",
    "Pitch and Tone - Total - AVERAGE",
    "Cross-Talk - Total - AVERAGE",
    "Emotion Detection - Total - AVERAGE",
    "Silence and Hold Time - Total - AVERAGE",
    "Resolution of the Call - Total - AVERAGE",
    "OPEN - AVERAGE",
    "SOLVE - AVERAGE",
    "DEEPEN RELATIONSHIP - AVERAGE",
    "CLOSE WITH CONFIDENCE - AVERAGE",
    "VIBES",
    "Q1",
    "Q2",
    "Q3",
    "Q4",
    "VIBES Target",
    "HOC - Met",
    "VG Error - Met",
    "Hotline - Met",
    "PP Error - Met",
    "Error - Met",
    "Listen - Met",
    "Acknowledge - Met",
    "Explore - Met",
    "Recommend - Met",
    "VG LAER - Met",
    "RTF - Met",
    "CFR - Met",
    "CHT - Met",
    "Complaints - Met",
    "Sales Practice Review",
    "Business Integrity",
    "Misconduct Behavior",
    "Severity Level",
    'CCP',
    'Acknowledge',
    "Explore CVP and Identify Clues",
    "Listen and Discover",
    "Connect a Relevant Offer",
    "Transition with a Relevant Statement",
    "Communicate Features of the Offer",
    "Personalize Value and Benefit",
    "Process the Offer Compliantly",
    "Offer Status","Offer Type"
]

dump_to_drop_columns = [
    'Monitor Date',
    'Call Date',
    "Feedback Date",
    "Spoken Words - OPEN",
    "Spoken Words - SOLVE",
    "Spoken Words - DEEPEN RELATIONSHIP",
    "Spoken Words - CLOSE WITH CONFIDENCE",
    "Pitch and Tone - OPEN",
    "Pitch and Tone - SOLVE",
    "Pitch and Tone - DEEPEN RELATIONSHIP",
    "Pitch and Tone - CLOSE WITH CONFIDENCE",
    "Cross-Talk - OPEN",
    "Cross-Talk - SOLVE",
    "Cross-Talk - DEEPEN RELATIONSHIP",
    "Cross-Talk - CLOSE WITH CONFIDENCE",
    "Emotion Detection - OPEN",
    "Emotion Detection - SOLVE",
    "Emotion Detection - DEEPEN RELATIONSHIP",
    "Emotion Detection - CLOSE WITH CONFIDENCE",
    "Silence and Hold Time - OPEN",
    "Silence and Hold Time - SOLVE",
    "Silence and Hold Time - DEEPEN RELATIONSHIP",
    "Silence and Hold Time - CLOSE WITH CONFIDENCE",
    "Resolution of the Call - OPEN",
    "Resolution of the Call - SOLVE",
    "Resolution of the Call - DEEPEN RELATIONSHIP",
    "Resolution of the Call - CLOSE WITH CONFIDENCE",
    "CCP",
    "CCP_1",
    "TL",
    "FIG",
    "Caller Type",
    "Explore CVP and Identify Clues",
    "Listen and Discover",
    "Connect a Relevant Offer",
    "Transition with a Relevant Statement",
    "Communicate Features of the Offer",
    "Personalize Value and Benefit",
    "Process the Offer Compliantly",
    "Offer Status",
    "Offer Type", 
]